apiVersion: 'app.sealos.io/v1'
kind: Template
metadata:
  name: minecraft
spec:
  title: 'Minecraft Server'
  author: 'Sealos'
  description: 'minecraft server'
  templateType: inline
  url: 'https://docker-minecraft-server.readthedocs.io/en/latest/'
  gitRepo: 'https://github.com/itzg/docker-minecraft-server'
  readme: 'https://github.com/itzg/docker-minecraft-server/blob/master/README.md'
  draft: true
  defaults:
    app_name:
      type: string 
      value: minecraft-${{ random(8) }}
  inputs:
    IMAGE:
      description: "image name"
      type: string
      default: "itzg/minecraft-server"
      required: true
    TYPE:
      description: "server type"
      type: choice
      options:
        - "FORGE"
        - "FABRIC"
        - "PAPER"
      default: "PAPER"
      required: true
    VERSION:
      description: "minecraft version"
      type: string
      default: "LATEST"
      required: true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${{ defaults.app_name }}
  annotations:
    originImageName: ${{ inputs.IMAGE }}
    deploy.cloud.sealos.io/minReplicas: "1"
    deploy.cloud.sealos.io/maxReplicas: "1"
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
    app: ${{ defaults.app_name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  serviceName: ${{ defaults.app_name }}
  selector:
    matchLabels:
      app: ${{ defaults.app_name }}
  template:
    metadata:
      labels:
        app: ${{ defaults.app_name }}
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: take-data-dir-ownership
          image: alpine
          command: ["/bin/sh", "-c", "chown -R 1000:1000 /data; chmod -R 770 /data"]
          volumeMounts:
            - name: vn-minecraft
              mountPath: /data
      containers:
        - name: ${{ defaults.app_name }}
          image: ${{ inputs.IMAGE }}
          imagePullPolicy: IfNotPresent
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: ${{ inputs.TYPE }}
            - name: VERSION
              value: ${{ inputs.VERSION }}
            - name: REMOVE_OLD_MODS
              value: "false"
            - name: PLUGINS
              value: ""
            - name: MODS
              value: ""    
            - name: MODPACK
              value: ""
          volumeMounts:
            - mountPath: /data
              name: vn-minecraft
          ports:
            - containerPort: 25565
              name: game
          readinessProbe:
            exec:
              command:
                - mc-monitor
                - status 
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 20
          resources:
            requests:
              cpu: 1000m
              memory: 2048Mi
              ephemeral-storage: 400Mi
            limits:
              cpu: 4000m
              memory: 8192Mi
              ephemeral-storage: 400Mi
  volumeClaimTemplates:
    - metadata:
        name: vn-minecraft
        annotations:
          path: /data
          value: "2"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ${{ defaults.app_name }}
  labels:
    cloud.sealos.io/app-deploy-manager: ${{ defaults.app_name }}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      name: game
  selector:
    app: ${{ defaults.app_name }}
